---
title: "SMU_DDS_CASE_STUDY_2"
author: "Rashmi Patel"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(tidyverse)
library(caret)
library(DataExplorer)
library(gplots)
library(graphics)
library(corrplot)
library(olsrr)
library(ggpubr)
library(rstatix)
library(dplyr)
library(tidyverse)
library(visdat)
library(GGally)
library(usmap)
library(mice)
library(VIM)
library(plotly)
library(caret)
library(e1071)
library(class)
library(maps)
library(mapproj)
library(stringr)
library(ggplot2) 
library(ggthemes)
library(table1)
library(DataExplorer)



``` 

```{r}
case2 = read.csv("https://raw.githubusercontent.com/RashmiAPatel19/SMU_MSDS_6306_CaseStudy2_Spring2021/main/CaseStudy2-data.csv", header = TRUE)
head(case2)
dim(case2)
plot_histogram(case2)
str(case2)
```
```{r}
case2_transformed <- case2
case2_transformed["logDistanceFromHome"] = log(case2_transformed$DistanceFromHome)
plot_histogram(case2_transformed$DistanceFromHome)
plot_histogram(case2_transformed$logDistanceFromHome)

case2_transformed["logMonthlyIncome"] = log(case2_transformed$MonthlyIncome)
plot_histogram(case2_transformed$MonthlyIncome)
plot_histogram(case2_transformed$logMonthlyIncome)

case2_transformed["logNumCompaniesWorked"] = log(case2_transformed$NumCompaniesWorked)
plot_histogram(case2_transformed$NumCompaniesWorked)
plot_histogram(case2_transformed$logNumCompaniesWorked)


case2_transformed["logPercentSalaryHike"] = log(case2_transformed$PercentSalaryHike)
plot_histogram(case2_transformed$PercentSalaryHike)
plot_histogram(case2_transformed$logPercentSalaryHike)

case2_transformed["logTotalWorkingYears"] = log(case2_transformed$TotalWorkingYears)
plot_histogram(case2_transformed$TotalWorkingYears)
plot_histogram(case2_transformed$logTotalWorkingYears)

case2_transformed["logYearsInCurrentRole"] = log(case2_transformed$YearsInCurrentRole)
plot_histogram(case2_transformed$YearsInCurrentRole)
plot_histogram(case2_transformed$logYearsInCurrentRole)

case2_transformed["logYearsSinceLastPromotion"] = log(case2_transformed$YearsSinceLastPromotion)
plot_histogram(case2_transformed$YearsSinceLastPromotion)
plot_histogram(case2_transformed$logYearsSinceLastPromotion)




```
```{r}
colnames(case2)
age=sum(is.na(case2$Age))
age
unique(case2$Attrition)
attr=sum(is.na(case2$Attrition))
attr

unique(case2$BusinessTravel)
travel=sum(is.na(case2$BusinessTravel))
travel

unique(case2$DailyRate)
dailyrate=sum(is.na(case2$DailyRate))
dailyrate
unique(case2$Department)
dept=sum(is.na(case2$Department))
dept
unique(case2$DistanceFromHome)
dist_home=sum(is.na(case2$DistanceFromHome))
dist_home
unique(case2$Education)
education=sum(is.na(case2$Education))
education
unique(case2$EducationField)
educ_field=sum(is.na(case2$EducationField))
educ_field
unique(case2$EmployeeNumber)
emp_num=sum(is.na(case2$EmployeeNumber))
emp_num
unique(case2$EnvironmentSatisfaction)
env_satisfaction=sum(is.na(case2$EnvironmentSatisfaction))
env_satisfaction
unique(case2$Gender)
gender=sum(is.na(case2$Gender))
gender
unique(case2$HourlyRate)
hourlyrate=sum(is.na(case2$HourlyRate))
hourlyrate
unique(case2$JobInvolvement)
job_involvement=sum(is.na(case2$JobInvolvement))
job_involvement
unique(case2$JobLevel)
job_level=sum(is.na(case2$JobLevel))
job_level
unique(case2$JobRole)
job_role=sum(is.na(case2$JobRole))
job_role
unique(case2$JobSatisfaction)
job_statisfaction=sum(is.na(case2$JobSatisfaction))
job_statisfaction
unique(case2$MaritalStatus)
marital_status=sum(is.na(case2$MaritalStatus))
marital_status
unique(case2$MonthlyIncome)
monthly_income=sum(is.na(case2$MonthlyIncome))
monthly_income
unique(case2$MonthlyRate)
monthly_rate=sum(is.na(case2$MonthlyRate))
monthly_rate
unique(case2$NumCompaniesWorked)
num_company_worked=sum(is.na(case2$NumCompaniesWorked))
num_company_worked
unique(case2$Over18)
over_18=sum(is.na(case2$Over18))
over_18
unique(case2$OverTime)
overtime=sum(is.na(case2$OverTime))
overtime
unique(case2$PercentSalaryHike)
percent_salary_hike=sum(is.na(case2$PercentSalaryHike))
percent_salary_hike
unique(case2$PerformanceRating)
performance_rating=sum(is.na(case2$PerformanceRating))
performance_rating
unique(case2$RelationshipSatisfaction)
relation_satisfaction=sum(is.na(case2$RelationshipSatisfaction))
relation_satisfaction
unique(case2$StandardHours)
standard_hours=sum(is.na(case2$StandardHours))
standard_hours
unique(case2$StockOptionLevel)
stock_option_level=sum(is.na(case2$StockOptionLevel))
stock_option_level
unique(case2$TotalWorkingYears)
total_working_years=sum(is.na(case2$TotalWorkingYears))
total_working_years

unique(case2$TrainingTimesLastYear)
training_lastyear=sum(is.na(case2$TrainingTimesLastYear))
training_lastyear
unique(case2$WorkLifeBalance)
work_life_balance=sum(is.na(case2$WorkLifeBalance))
work_life_balance
unique(case2$YearsAtCompany)
years_at_company=sum(is.na(case2$YearsAtCompany))
years_at_company
unique(case2$YearsInCurrentRole)
years_current_role=sum(is.na(case2$YearsInCurrentRole))
years_current_role
unique(case2$YearsSinceLastPromotion)
years_last_promotion=sum(is.na(case2$YearsSinceLastPromotion))
years_last_promotion
unique(case2$YearsWithCurrManager)
years_cuurent_manager=sum(is.na(case2$YearsWithCurrManager))
years_cuurent_manager


```

# Factors:
## BusinessTravel
## Department
## EducationField
## Gender
## JobRole
## MaritalStatus
## Over18
## OverTime
```{r}


```
```{r}
summary(case2$JobRole)

jobrole_healthcare_rep=case2%>%select(JobRole)%>%filter(JobRole=="Healthcare Representative")
length(jobrole_healthcare_rep$JobRole)

jobrole_hr=case2%>%select(JobRole)%>%filter(JobRole=="Human Resources")
length(jobrole_hr$JobRole)

jobrole_lab_tech=case2%>%select(JobRole)%>%filter(JobRole=="Laboratory Technician")
length(jobrole_lab_tech$JobRole)

jobrole_manager=case2%>%select(JobRole)%>%filter(JobRole=="Manager")
length(jobrole_manager$JobRole)

jobrole_manf_dir=case2%>%select(JobRole)%>%filter(JobRole=="Manufacturing Director")
length(jobrole_manf_dir$JobRole)

jobrole_research_dir=case2%>%select(JobRole)%>%filter(JobRole=="Research Director")
length(jobrole_research_dir$JobRole)

jobrole_research_scientist=case2%>%select(JobRole)%>%filter(JobRole=="Research Scientist")
length(jobrole_research_scientist$JobRole)

jobrole_sales_exe=case2%>%select(JobRole)%>%filter(JobRole=="Sales Executive")
length(jobrole_sales_exe$JobRole)

jobrole_sales_rep=case2%>%select(JobRole)%>%filter(JobRole=="Sales Representative")
length(jobrole_sales_rep$JobRole)

case2_jobrole_count=data.frame(Jobrole=c("Sales Executive","Research Director","Manufacturing Director","Research Scientist","Sales Representative","Healthcare Representative","Manager","Human Resources","Laboratory Technician"),Count=c(200,51,87,172,53,76,51,27,153))
case2_jobrole_count

ggplot(case2_jobrole_count,aes(x=Count,y=Jobrole,fill=Jobrole))+geom_col()+
  xlab("Number of Employees Per Job Role")+ylab("Job Role for Employees")+
  ggtitle("Number of Employees in each Job Role")

summary(case2$MonthlyIncome)

 
ggplot(case2,aes(x=MonthlyIncome,y=JobRole,fill=JobRole))+geom_point()+
   theme(axis.text.x = element_text(angle = 90))



```
```{r}
case2$Attrition=as.numeric(case2$Attrition)
case2$BusinessTravel=as.numeric(case2$BusinessTravel)

attr_income=data.frame(case2$Attrition,case2$MonthlyIncome)
head(attr_income)
str(attr_income)
  
cor(attr_income)
cor(case2$Attrition,case2$BusinessTravel)
```
```{r}



```
```{r}



```